Port Project Keter's test runner to this project
rust-windowing/winit-next pull request #3
Opened 2024-01-08 22:49 UTC by notgull

As discussed in chat, ports the test framework I wrote for testing Project Keter to winit. Hopefully useful for making sure everything works in CI.

Not really CI-ready yet. I need to upload all of the Docker images first.

2024-01-09 03:53 UTC, kchibisov requested changes
I haven't looked into how it actually works, but in general, you shouldn't touch `winit-core`. You should test the `winit` stuff, the core is irrelevant?

It'll also be nice to have some sort of CI for stuff like that to actually see how it could be used and what we can achieve with that.

Given that it doesn't interact with the winit stuff itself  yet it could leave on this branch for now unless we have it actually wired with real tests on platforms supporting that, if it's fine with you.

2024-01-09 03:53 UTC, kchibisov commented on winit-core/winit_tests/hello_world/src/lib.rs
> +        });
Do we really need any tests here? This doesn't have any core logic stuff it should all go into the `winit` crate instead.

2024-01-12 13:48 UTC, daxpedda commented
Is this capable of running integration tests of Winit? E.g. resizing a window and checking if the correct events are fired?

2024-01-12 16:38 UTC, notgull commented
Not yet; it's just a test runner for now

2025-12-24 20:25 UTC, closed without merging